x-base-service: &base-service
  restart: unless-stopped
  build:
    context: .
    target: development
    args:
      USER_ID: ${UID:-1000}
      GROUP_ID: ${GID:-1000}
      PHP_VERSION: 8.3
  volumes:
    - .:/var/www/html:cached
  networks:
    - nginx-proxy-manager-network

services:
  grd-filament:
    <<: *base-service
    container_name: grd-filament
    working_dir: /var/www/html
    # healthcheck:
    #   test: ["CMD", "test", "-f", "/var/www/html/vendor/autoload.php"]
    #   interval: 5s
    #   timeout: 10s
    #   retries: 3
    #   start_period: 10s

  task:
    <<: *base-service
    container_name: grd-filament-task
    command: ["php", "/var/www/html/artisan", "schedule:work"]
    stop_signal: SIGTERM
    healthcheck:
      test: ["CMD", "/usr/local/bin/healthcheck-schedule"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    depends_on:
      grd-filament:
        condition: service_healthy

  queue:
    <<: *base-service
    container_name: grd-filament-queue
    command: ["php", "/var/www/html/artisan", "queue:work", "--tries=3"]
    stop_signal: SIGTERM
    healthcheck:
      test: ["CMD", "healthcheck-queue"]
      start_period: 10s
    depends_on:
      grd-filament:
        condition: service_healthy

  reverb:
    <<: *base-service
    container_name: grd-filament-reverb
    command: ["php", "/var/www/html/artisan", "reverb:start", "--host=0.0.0.0", "--port=8000"]
    stop_signal: SIGTERM
    ports:
      - 8000:8000
    healthcheck:
      test: ["CMD", "healthcheck-reverb"]
      start_period: 10s

networks:
  nginx-proxy-manager-network:
    external: true
